# Generated by Django 3.1.2 on 2020-10-23 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libro', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('idPrestamo', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaPrestamo', models.DateTimeField()),
                ('fechaDevolucion', models.DateTimeField()),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuarios')),
                ('idlibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.libros')),
            ],
        ),
    ]
